### ISSUE TITLE
提交一个bug

### ISSUE THREAD

**Issue by dytxy888** [wenet-e2e/WeTextProcessing#114]
[root@localhost WeTextProcessing]# python -m itn --text "二十一到二十五摄氏度"
math { value: "21\~2" } measure { value: "15°C" }
21~215°C

输出21~215°C，不符合预期。

**Comment by xingchensong** [comment]
收到，马上解决

**Comment by xingchensong** [comment]
已解决 https://github.com/wenet-e2e/WeTextProcessing/pull/115

同时也考虑了其他的说法：百分之二十到百分之三十，百分之二十到三十，每小时十到十五千米，十到十五千米每小时 之类的
