### ISSUE TITLE
[ITN] English ITN crashes 

### ISSUE THREAD

**Issue by pashalot** [wenet-e2e/WeTextProcessing#118]
Hello!

I'm trying to use c++ implementation for English ITN with tagger and verbalizer from Nemo library. 
The problem is that verbalizer crashes because of `TokenParser`.
Here is an example.

input: 
`this is the first test`

tagger output: 
`tokens { name: "this" } tokens { name: "is" } tokens { name: "the" } tokens { ordinal { integer: "1" } } tokens { name: "test" }`

parser output: 
`tokens { name: "this" } tokens { name: "is" } tokens { name: "the" } tokens { ordinal: "{ integer: " : "1" }  { } tokens { name: "test" }`

The parser output seems a bit odd adding some random quotation marks and brackets.
Removing parser before verbalizer makes everything work as expected (credits to @ezerhouni for pointing this out). 

Could you help with solving this in a more neat way on a parser side maybe? 

Thanks in advance!

**Comment by xingchensong** [comment]
Our output format is different from nemo, we do not include `tokens`, We used a two-level dictionary like this:

`name { value: "this" } name { value: "is" } name { value: "the" } ordinal { value: "1" } name { value: "test" }`

**Comment by xingchensong** [comment]
if u want to use fst compiled from nemo, u need to modify token_parser.cc yourself, currently we do not have time to do so
