### ISSUE TITLE
badcase  十七八万 转换成了 1070000~80000，预计想输出170000~180000

### ISSUE THREAD

**Issue by xiaomingnio** [wenet-e2e/WeTextProcessing#121]
badcase  十七八万 转换成 1070000~80000，请问这种该如何修改？

**Comment by xingchensong** [comment]
今天给修复一下，稍晚一点

**Comment by xingchensong** [comment]
预期输出是什么，这里存在歧义，一方面可以理解为7w-10w，表达一个范围。另一方面可以理解为17w到18w。

**Comment by xiaomingnio** [comment]
预计输出十七万到十八万

**Comment by xiaomingnio** [comment]
另外可以支持车牌号的逆正则吗？

**Comment by xingchensong** [comment]
> 另外可以支持车牌号的逆正则吗？   

可以，给几个例子？特别是口语化的那种，比如 皖a152bc，语音识别可能识别成皖哎一五二逼c？

**Comment by xingchensong** [comment]
> 例如语音识别为鄂a七l六二u，想转换为鄂A7L62U

车牌号这个可以单独提一个issue吗，方便管理需求

**Comment by xiaomingnio** [comment]
好的

**Comment by xingchensong** [comment]
这种口语化的表达是不是只有10-20这个区间才有，感觉超过20有点别扭，比如四十五六，三百一二

**Comment by xiaomingnio** [comment]
回答年龄的时候有可能会说四十五六岁这种，如果可以的话，感觉不转成阿拉伯数字比较好，有啥办法可以把这种口语化表达过滤了。

**Comment by xingchensong** [comment]
![image](https://github.com/wenet-e2e/WeTextProcessing/assets/13466943/07d86e1c-9662-47c6-9fc5-5bb641e61bee)

https://github.com/wenet-e2e/WeTextProcessing/pull/123

波浪号表示范围，破折号表示省略

**Comment by xingchensong** [comment]
Q: 为啥一个用 ~ 一个用 -
A: 四十五六没法转45~46，没法保留4的状态，45~46 等价表示为 45-6
