### ISSUE TITLE
bad case, 幺三二六二号 -> 1326~2号

### ISSUE THREAD

**Issue by HankLiu10** [wenet-e2e/WeTextProcessing#132]
您好，我想提供一个bad case，麻烦看看为什么会这么匹配：

weitn --text "哎您好这里市中心幺二三四五工号幺三二六二号"
char { value: "哎" } char { value: "您" } char { value: "好" } char { value: "这" } char { value: "里" } char { value: "市" } char { value: "中" } char { value: "心" } cardinal { value: "12345" } char { value: "工" } char { value: "号" } cardinal { value: "132" } measure { value: "6~2号" }
哎您好这里市中心12345工号1326~2号

这个”1326~2“里的”~“是怎么来的

**Comment by HankLiu10** [comment]
格式被吞了，重发一下

weitn --text "哎您好这里市中心幺二三四五工号幺三二六二号"
char { value: "哎" } char { value: "您" } char { value: "好" } char { value: "这" } char { value: "里" } char { value: "市" } char { value: "中" } char { value: "心" } cardinal { value: "12345" } char { value: "工" } char { value: "号" } cardinal { value: "132" } measure { value: "6\~2号" }
哎您好这里市中心12345工号1326\~2号

**Comment by xingchensong** [comment]
可以去掉 itn/chinese/data/measure/units_zh.tsv 中的 `号`

**Comment by HankLiu10** [comment]
> 可以去掉 itn/chinese/data/measure/units_zh.tsv 中的 `号`

是什么号，没找到

**Comment by xingchensong** [comment]
号是个单位，在文件 itn/chinese/data/measure/units_zh.tsv 中

**Comment by HankLiu10** [comment]
好的，谢谢

> 号是个单位，在文件 itn/chinese/data/measure/units_zh.tsv 中

**Comment by xingchensong** [comment]
@HankLiu10 可以提个PR
