### ISSUE TITLE
badcase咨询-连续四个数字转换失败

### ISSUE THREAD

**Issue by fxyouruo** [wenet-e2e/WeTextProcessing#133]
您好！今天测试的时候发现，三个或者四个以上数字能正常转换，但是四个数字的话，第一个转换失败，示例：
1）python -m itn --text "幺二三" --overwrite_cache
cardinal { value: "123" }
123

2）python -m itn --text "幺二三四" --overwrite_cache
char { value: "幺" } cardinal { value: "234" }
幺234

3）python -m itn --text "幺二三四五" --overwrite_cache
cardinal { value: "12345" }
12345

咨询一下是我版本的问题（2023.10.30下载），还是目前存在的问题呀？ 有解决的办法嘛？

谢谢！

**Comment by xingchensong** [comment]
这是预期现象，因为三个数字/五个数字可以用来表示电话号码。四个数字有什么有具体含义的场景（也就是用户什么情况下会说四个数字）？

**Comment by fxyouruo** [comment]
> 这是预期现象，因为三个数字/五个数字可以用来表示电话号码。四个数字有什么有具体含义的场景（也就是用户什么情况下会说四个数字）？

非常感谢回复！ ！！
遇到是的情况是，在客服场景，客服会报工号：您好，工号九五二七为您服务！  这样子的使用案例！

**Comment by xingchensong** [comment]
好的，等会修改，今天会release一个新版

**Comment by fxyouruo** [comment]
> 好的，等会修改，今天会release一个新版

赞赞赞！非常感谢！！！！

**Comment by xingchensong** [comment]
好了

**Comment by fxyouruo** [comment]
> 好了

谢谢，辛苦啦！！！
