### ISSUE TITLE
IP地址转换问题咨询

### ISSUE THREAD

**Issue by fxyouruo** [wenet-e2e/WeTextProcessing#135]
您好！今天在IP地址转换的时候发现一个问题：

1. python -m itn --text "**幺幺**点二三点四五点六七" => **11**.23.45.67
2. python -m itn --text "**幺零**点二三点四五点六七" => **幺0**.23.45.67

在最近的版本上尝试。

谢谢！

**Comment by xingchensong** [comment]
休假中，下周解决这个问题

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/WeTextProcessing/pull/138

**Comment by xingchensong** [comment]
感谢指正
