### ISSUE TITLE
How to use ITN in Wenet runtime?

### ISSUE THREAD

**Issue by mengyanggithub** [wenet-e2e/WeTextProcessing#14]
I'm new to Wenet, and want to use ITN in wenet runtime. I found out it is already done in the roadmap item 3: https://github.com/wenet-e2e/WeTextProcessing/issues/1#issuecomment-914349966. 
Could you please provide an example？

**Comment by xingchensong** [comment]
We have done supporting wenet-text-processing cmake build being a sub-project, see https://github.com/wenet-e2e/WeTextProcessing/pull/12. I will provide an example and integrate it into wenet this weekend.

**Comment by xingchensong** [comment]
@mengyanggithub u may refer to this https://github.com/wenet-e2e/wenet/pull/1310. BTW, we are going to refactor our post_processor thus this PR will not be merged, but I do think it's a good reference for demonstrating how to intergrate WeTextProssing into other projects.

**Comment by mengyanggithub** [comment]
> @mengyanggithub u may refer to this [wenet-e2e/wenet#1310](https://github.com/wenet-e2e/wenet/pull/1310). BTW, we are going to refactor our post_processor thus this PR will not be merged, but I do think it's a good reference for demonstrating how to intergrate WeTextProssing into other projects.

thx～
