### ISSUE TITLE
一些badcases

### ISSUE THREAD

**Issue by suzhenghang** [wenet-e2e/WeTextProcessing#152]
1 额外奖励50000票值->额外奖励五零零零零票值，期望应该是  "额外奖励5万票值"
2 独得300w张->得三零零w张，期望应该是3百万张
3 当场票数≥100万->当场票数≥一百万，期望应该是当场票数大于等于100万
4 22:58结束->十二点五十八分结束没问题，但是如果是22：58结束（中文冒号）->二二:五八结束

**Comment by xingchensong** [comment]
好的，收到
