### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by HankLiu10** [wenet-e2e/WeTextProcessing#158]
你好，我在一台aarch64架构的centos7.6机器安装时，出现如下报错，尝试诸多解决办法未果

麻烦看看能不能解决

以下是部分报错信息

      building '_pywrapfst' extension
      creating build/temp.linux-aarch64-cpython-38
      creating build/temp.linux-aarch64-cpython-38/extensions
      /usr/local/gcc7.3.0/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/python3.8.10/include/python3.8 -c extensions/_pywrapfst.cpp -o build/temp.linux-aarch64-cpython-38/extensions/_pywrapfst.o -std=c++17 -Wno-register -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
      extensions/_pywrapfst.cpp:813:10: fatal error: fst/util.h: No such file or directory
       #include <fst/util.h>
                ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/local/gcc7.3.0/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynini
Failed to build pynini
ERROR: Could not build wheels for pynini, which is required to install pyproject.toml-based projects

**Comment by HankLiu10** [comment]
补充，报错信息在运行 
pip install WeTextProcessing
时即出现

**Comment by xingchensong** [comment]
pip install pynini==2.1.5之后再install wetext试试

**Comment by HankLiu10** [comment]
> pip install pynini==2.1.5之后再install wetext试试

这个也试了，出现相同的报错

      /usr/local/gcc7.3.0/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/python3.8.10/include/python3.8 -c extensions/_pywrapfst.cpp -o build/temp.linux-aarch64-3.8/extensions/_pywrapfst.o -std=c++17 -Wno-register -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
      extensions/_pywrapfst.cpp:817:10: fatal error: fst/util.h: No such file or directory
       #include <fst/util.h>
                ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/local/gcc7.3.0/bin/gcc' failed with exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynini
  Running setup.py clean for pynini
Failed to build pynini
ERROR: Could not build wheels for pynini, which is required to install pyproject.toml-based projects

**Comment by HankLiu10** [comment]
> > pip install pynini==2.1.5之后再install wetext试试
> 
> 这个也试了，出现相同的报错
> 
> ```
>   /usr/local/gcc7.3.0/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/python3.8.10/include/python3.8 -c extensions/_pywrapfst.cpp -o build/temp.linux-aarch64-3.8/extensions/_pywrapfst.o -std=c++17 -Wno-register -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
>   extensions/_pywrapfst.cpp:817:10: fatal error: fst/util.h: No such file or directory
>    #include <fst/util.h>
>             ^~~~~~~~~~~~
>   compilation terminated.
>   error: command '/usr/local/gcc7.3.0/bin/gcc' failed with exit status 1
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pynini Running setup.py clean for pynini Failed to build pynini ERROR: Could not build wheels for pynini, which is required to install pyproject.toml-based projects

补充一下，这里出现相同的报错是pip install pynini==2.1.5时即出现问题

**Comment by xingchensong** [comment]
python什么版本

**Comment by HankLiu10** [comment]
> python什么版本

你好，是3.8.10

**Comment by HankLiu10** [comment]
> pynini 估计不支持 aarch64

好的，谢谢，那么我想点别的办法

**Comment by Chen1399** [comment]
> 你好，我在一台aarch64架构的centos7.6机器安装时，出现如下报错，尝试诸多解决办法未果
> 
> 麻烦看看能不能解决
> 
> 以下是部分报错信息
> 
> ```
>   building '_pywrapfst' extension
>   creating build/temp.linux-aarch64-cpython-38
>   creating build/temp.linux-aarch64-cpython-38/extensions
>   /usr/local/gcc7.3.0/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/python3.8.10/include/python3.8 -c extensions/_pywrapfst.cpp -o build/temp.linux-aarch64-cpython-38/extensions/_pywrapfst.o -std=c++17 -Wno-register -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
>   extensions/_pywrapfst.cpp:813:10: fatal error: fst/util.h: No such file or directory
>    #include <fst/util.h>
>             ^~~~~~~~~~~~
>   compilation terminated.
>   error: command '/usr/local/gcc7.3.0/bin/gcc' failed with exit code 1
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pynini Failed to build pynini ERROR: Could not build wheels for pynini, which is required to install pyproject.toml-based projects

你这个是没有安装openfst, openfst目录make install一下就好了

**Comment by Jackiexiao** [comment]
```
wget https://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.8.2.post1.tar.gz
tar -zxvf openfst-1.8.2.post1.tar.gz
cd openfst-1.8.2.post1 && ./configure && make && make install
```

**Comment by xiaoqiang-ok** [comment]
> ```
> wget https://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.8.2.post1.tar.gz
> tar -zxvf openfst-1.8.2.post1.tar.gz
> cd openfst-1.8.2.post1 && ./configure && make && make install
> ```
make报错：
![Image](https://github.com/user-attachments/assets/028e4560-b102-4ff3-820c-d4fab03b7aa5)
