### ISSUE TITLE
Bad Case，身份证号多了空格

### ISSUE THREAD

**Issue by HankLiu10** [wenet-e2e/WeTextProcessing#160]
python -m itn --text "我的身份证号是三四零二零三一九三七零幺零幺零五幺七"

识别结果是：我的身份证号是3402 031 93701010517

貌似多了两个空格

**Comment by xingchensong** [comment]
好，收到，明天看

**Comment by xingchensong** [comment]
fixed  https://github.com/wenet-e2e/WeTextProcessing/pull/161
