### ISSUE TITLE
对money转写的疑问

### ISSUE THREAD

**Issue by HankLiu10** [wenet-e2e/WeTextProcessing#162]
你好，想提一个比较水的问题，
我观察到用itn转换如“九美元”，仍能识别为money，并给出“$9”的正确转写，
阅读money.py规则代码时，发现number |= digit + insert("~") + digit，即匹配如“七八美元”的输入
请问如何识别单个数字呢
请问是通过
        ```number = Cardinal().number if self.enable_0_to_9 else \
            Cardinal().number_exclude_0_to_9```
吗

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/WeTextProcessing/blob/master/itn/chinese/rules/cardinal.py

**Comment by HankLiu10** [comment]
好的，谢谢
