### ISSUE TITLE
关于货币最小单位的支持

### ISSUE THREAD

**Issue by HankLiu10** [wenet-e2e/WeTextProcessing#163]
目前货币单位似乎不支持对“角”、“毛”、“分”等的识别

比如，“四元五角”、“八块五”等

**Comment by xingchensong** [comment]
![image](https://github.com/wenet-e2e/WeTextProcessing/assets/13466943/8ff8e61d-9c75-4728-ace6-b8cca1d65ca7)

**Comment by HankLiu10** [comment]
![image](https://github.com/wenet-e2e/WeTextProcessing/assets/29350711/5acd56b7-326c-4a65-b00e-b06ddc23526a)
有点怪

**Comment by xingchensong** [comment]
什么场景下会精确到角毛分

**Comment by HankLiu10** [comment]
你好，查询话费时，有时会精确到分

**Comment by xingchensong** [comment]
- https://github.com/wenet-e2e/WeTextProcessing/blob/master/itn/chinese/rules/money.py  元
- https://github.com/wenet-e2e/WeTextProcessing/blob/master/itn/chinese/rules/measure.py 毛/分

**Comment by xingchensong** [comment]
改起来有点麻烦，捏可以先尝试一下自己修改，我稍晚push一个，就当对比学习了

**Comment by HankLiu10** [comment]
> 改起来有点麻烦，捏可以先尝试一下自己修改，我稍晚push一个，就当对比学习了

我也是这么打算的，感谢！

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/WeTextProcessing/commit/b68409a52d4c1313042106c1e66b517ccdd4a970

![img_v3_025d_f1faca82-a11d-47d6-92d2-ff7c02f7669g](https://github.com/wenet-e2e/WeTextProcessing/assets/13466943/1f82e26f-1d5e-4d16-b80b-cc90fde01827)
