### ISSUE TITLE
Compose结果为空

### ISSUE THREAD

**Issue by Ryuk17** [wenet-e2e/WeTextProcessing#164]
我运行processor_main时发现input不为空时，输出结果为空。打印位置和运行结果如下所示。为了和wenet一起使用，openfst版本为1.6.5。

![image](https://github.com/wenet-e2e/WeTextProcessing/assets/22525811/780ee371-f54c-4e8c-9d84-6585d1ad04d8)

![image](https://github.com/wenet-e2e/WeTextProcessing/assets/22525811/99b71833-f8a8-46b5-bb1b-ab660a277a0c)

**Comment by Ryuk17** [comment]
这是输入文本“1988年10月1日下午3:25给了我5000块钱”

**Comment by Ryuk17** [comment]
升级到1.7.2没有这个问题了，谢谢

**Comment by pengzhendong** [comment]
> 升级到1.7.2没有这个问题了，谢谢

更新到 1.7.2 了，可以试试：

https://jitpack.io/#pengzhendong/wenet-openfst-android/1.0.3
