### ISSUE TITLE
安卓端编译报错

### ISSUE THREAD

**Issue by qweasdzxcvde** [wenet-e2e/WeTextProcessing#169]
大佬们，编译runtime/android 报如下错误，请问这个应该怎么解决呢？
![2023-11-29 14-59-19](https://github.com/wenet-e2e/WeTextProcessing/assets/35418904/033c4e0d-e3a4-4f55-bbb7-16ffeb911f88)

**Comment by qweasdzxcvde** [comment]
![Uploading 2023-11-29 14-59-19.png…]()

**Comment by xingchensong** [comment]
是不是没联网，openfst没下载成功

**Comment by qweasdzxcvde** [comment]
如果直接编译报下面这个错误，然后
![2023-12-0](https://github.com/wenet-e2e/WeTextProcessing/assets/35418904/fcb056b6-cf73-429e-963f-7b57d0359a19)

**Comment by qweasdzxcvde** [comment]
已解决

**Comment by xingchensong** [comment]
可以把解决方法贴一下，方便后面的同学遇到相同问题有解法

**Comment by qweasdzxcvde** [comment]
我发现找不到openfst是因为那个路径找不到，所以我试着把android-openfst的那个目录放入cpp目录下
![1](https://github.com/wenet-e2e/WeTextProcessing/assets/35418904/fb4882e1-36e5-428e-9d94-1ea6784f6ea7)
然后修改CMakeLists.txt中的 build_DIR 为 ${CMAKE_SOURCE_DIR}
同时修改最后一行 编译静态库为动态库
![2023-12-01](https://github.com/wenet-e2e/WeTextProcessing/assets/35418904/19c6fd68-2e7b-45b6-812a-5ba02b11b251)
这样编译成功。
这个是我的编译方法，可能是我编译的时候哪里没做对，引发这个错误，我的解决方法是这样的
