### ISSUE TITLE
数字的ITN

### ISSUE THREAD

**Issue by abcdbosh** [wenet-e2e/WeTextProcessing#188]
需求是添加一些数字的ITN，比如两>2，洞>0,拐>7,该如何修改呢

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/WeTextProcessing/blob/master/itn/chinese/data/number/digit.tsv 这里加，可以提个PR

**Comment by abcdbosh** [comment]
只需要修改这个tsv文件吗？我pip安装，将需求的numeber添加到了库内的tsv文件，但是没有效果，

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/WeTextProcessing/issues/185

**Comment by abcdbosh** [comment]
感谢您的回复，成功生成了新的fst，但是问题还是不能解决，比如洞八，幺两就不能实现ITN，但是四个字的比如：六六拐两就可以~有没有什么办法呢！

**Comment by xingchensong** [comment]
你需要enable_0_to_9=True
