### ISSUE TITLE
电话号码itn错误率非常高

### ISSUE THREAD

**Issue by pony5551** [wenet-e2e/WeTextProcessing#189]
<img width="670" alt="微信图片_20240304165747" src="https://github.com/wenet-e2e/WeTextProcessing/assets/36391163/6b6f0290-7811-4b76-814e-b7c8513f5ef8">

**Comment by xingchensong** [comment]
您好，无法复现您这个错误
![image](https://github.com/wenet-e2e/WeTextProcessing/assets/13466943/ec1ee647-059c-477e-b5c2-341ba8ba21b1)

**Comment by pony5551** [comment]
抱歉，验证是asr的问题
