### ISSUE TITLE
The "remove_erhua" and "remove_interjections" NOT WORK?

### ISSUE THREAD

**Issue by howitry** [wenet-e2e/WeTextProcessing#192]
command:
   from tn.chinese.normalizer import Normalizer
   normalizer = Normalizer(remove_interjections=False,remove_erhua=False)
   normalizer.normalize("2.5平方电线啊儿")
Output:
   二点五平方电线

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/WeTextProcessing/issues/185
