### ISSUE TITLE
时间转换错误

### ISSUE THREAD

**Issue by dospeech** [wenet-e2e/WeTextProcessing#199]
文本输入是“下午三点三十分”会被转为3:30.pm.
当想输出为“下午3:30分”时修改如下：
time.tsv里面pm改为下午，同时将time.py的
 verbalizer = (hour + addcolon + minute + (addcolon + second).ques +
                       noon.ques)
改为
verbalizer = (noon.ques  + hour + addcolon + minute + insert('分') +
                    (addcolon + second).ques)

结果报错如下：
  File "/mnt/weTextProcessing/tn/processor.py", line 96, in normalize
    return self.verbalize(self.tag(input))
  File "/mnt/weTextProcessing/tn/processor.py", line 93, in verbalize
    return shortestpath(lattice, nshortest=1, unique=True).string()
  File "extensions/_pynini.pyx", line 462, in _pynini.Fst.string
  File "extensions/_pynini.pyx", line 507, in _pynini.Fst.string
_pywrapfst.FstOpError: Operation failed
请问大佬，该怎么改，是不是我哪里改的不对？

**Comment by weimeng23** [comment]
tagger = (insert('hour: "') + h + insert('"') + insert(' minute: "') +
                  m + add_weight(delete('分'), -0.1).ques + insert('"') +
                  (insert(' second: "') + s + insert('"')).ques)

verbalizer = (hour + addcolon + minute + (addcolon + second).ques)

这是不动tokenparser的方案
