### ISSUE TITLE
"三四万"转换正确，但是“三四十万“转化错误

### ISSUE THREAD

**Issue by vbiwuevbaeib** [wenet-e2e/WeTextProcessing#232]
”三四十万“会被理解为”三四  十万“，这种问题应该怎么修改优化呢？

>>> invnormalizer.normalize("需要三四万")          
char { value: "需" } char { value: "要" } cardinal { value: "3~4万" }
'需要3~4万'
>>> invnormalizer.normalize("需要三四十万")
char { value: "需" } char { value: "要" } cardinal { value: "3~4 100000" }
'需要3~4 100000'

**Comment by vbiwuevbaeib** [comment]
还有像整数+约数范围，有时候也会出错，比如：
>>> invnormalizer.normalize("需要一万六七")                     
char { value: "需" } char { value: "要" } cardinal { value: "10000 6~7" }
'需要10000 6~7'

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/WeTextProcessing/pull/234 修好了

**Comment by vbiwuevbaeib** [comment]
可以了，非常感谢！
