### ISSUE TITLE
一个问题咨询

### ISSUE THREAD

**Issue by skywuxuan** [wenet-e2e/WeTextProcessing#244]
你好，我最近在写一些新的规则，举例一个修改：
file: WeTextProcessing/tn/chinese/rules/fraction.py

"""
    def build_verbalizer(self):
        denominator = delete('denominator: "') + self.SIGMA + delete('" ')
        numerator = delete('numerator: "') + self.SIGMA + delete('"')
        verbalizer = denominator + insert('分之') + numerator    ===修改成===>   verbalizer = numerator + insert('分之') + denominator
        self.verbalizer = self.delete_tokens(verbalizer)
"""
这类顺序变换会引起报错，请问下原因，万分感谢！

**Comment by pengzhendong** [comment]
> 你好，我最近在写一些新的规则，举例一个修改： file: WeTextProcessing/tn/chinese/rules/fraction.py
> 
> """ def build_verbalizer(self): denominator = delete('denominator: "') + self.SIGMA + delete('" ') numerator = delete('numerator: "') + self.SIGMA + delete('"') verbalizer = denominator + insert('分之') + numerator ===修改成===> verbalizer = numerator + insert('分之') + denominator self.verbalizer = self.delete_tokens(verbalizer) """ 这类顺序变换会引起报错，请问下原因，万分感谢！

token_parser.py 是需要按照原来的规则解析的。

**Comment by skywuxuan** [comment]
> > 你好，我最近在写一些新的规则，举例一个修改： file: WeTextProcessing/tn/chinese/rules/fraction.py
> > """ def build_verbalizer(self): denominator = delete('denominator: "') + self.SIGMA + delete('" ') numerator = delete('numerator: "') + self.SIGMA + delete('"') verbalizer = denominator + insert('分之') + numerator ===修改成===> verbalizer = numerator + insert('分之') + denominator self.verbalizer = self.delete_tokens(verbalizer) """ 这类顺序变换会引起报错，请问下原因，万分感谢！
> 
> token_parser.py 是需要按照原来的规则解析的。需要给出具体的错误才好分析

ERROR: StringFstToOutputLabels: Invalid start state
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    normalizer.normalize("1/3")
  File "./src/WeTextProcessing/tn/processor.py", line 130, in normalize
    return self.verbalize(self.tag(input))
  File "./src/WeTextProcessing/tn/processor.py", line 127, in verbalize
    return shortestpath(lattice, nshortest=1, unique=True).string()
  File "extensions/_pynini.pyx", line 462, in _pynini.Fst.string
  File "extensions/_pynini.pyx", line 507, in _pynini.Fst.string
_pywrapfst.FstOpError: Operation failed
具体报错错误信息如上。谢谢

**Comment by pengzhendong** [comment]
错误表示 verbalizer 无法解析你给的输入（即 tagger 的输出）

**Comment by pengzhendong** [comment]
> 大佬，如果我现在需要修改verbalizer的规则：在./tn/chinese/rules/fraction.py， verbalizer = denominator + insert('分之') + numerator 需要把 “denominator” 和 "numerator" 对调位置，其他代码中我应该修改什么位置才能保证链路跑通

改这行代码中分子和分母的顺序：https://github.com/wenet-e2e/WeTextProcessing/blob/790132c5f708fedc10c6929c22e389e7f371e4c4/tn/token_parser.py#L20

**Comment by skywuxuan** [comment]
> > 大佬，如果我现在需要修改verbalizer的规则：在./tn/chinese/rules/fraction.py， verbalizer = denominator + insert('分之') + numerator 需要把 “denominator” 和 "numerator" 对调位置，其他代码中我应该修改什么位置才能保证链路跑通
> 
> 改这行代码中分子和分母的顺序：
> 
> https://github.com/wenet-e2e/WeTextProcessing/blob/790132c5f708fedc10c6929c22e389e7f371e4c4/tn/token_parser.py#L20

这个点我之前就修改过，一样的报错...

**Comment by pengzhendong** [comment]
你先打印 tagger 的输出和 reorder 的输出

**Comment by skywuxuan** [comment]
> 你先打印 tagger 的输出和 reorder 的输出

tagger:     'fraction { numerator: "三" denominator: "一" } char { value: "的" } char { value: "人" }'
reorder:    'fraction { numerator: "三" denominator: "一" } char { value: "的" } char { value: "人" }'
ps 代码的改动点就 WeTextProcessing/tn/chinese/rules/fraction.py 和 WeTextProcessing/tn/token_parser.py 的两处

**Comment by pengzhendong** [comment]
你 reorder 的输出是 numerator 在前，但是你 verbalizer 先解析 denominator，所以就报错了。

**Comment by skywuxuan** [comment]
> 你 reorder 的输出是 numerator 在前，但是你 verbalizer 先解析 denominator，所以就报错了。

verbalizer的解析顺序应该是在tn/chinese/rules/fraction.py定义的吧，目前顺序就是verbalizer = numerator + insert('XX') + denominator  ；莫非还有其他地方影响这个顺序

**Comment by pengzhendong** [comment]
注意空格的处理：

``` python
denominator = delete('denominator: "') + self.SIGMA + delete('" ')
numerator = delete('numerator: "') + self.SIGMA + delete('"')
```

改成：

``` python
denominator = delete('denominator: "') + self.SIGMA + delete('"')
numerator = delete('numerator: "') + self.SIGMA + delete('" ')
```

**Comment by skywuxuan** [comment]
感谢^_^  ...
