### ISSUE TITLE
mac m1 report error 

### ISSUE THREAD

**Issue by fastfading** [wenet-e2e/WeTextProcessing#245]
mac 14.4.1 (23E224)
pip install cpython
brew install openfst
export CPLUS_INCLUDE_PATH=/opt/homebrew/opt/openfst/include:$CPLUS_INCLUDE_PATH
pip install WeTextProcessing
  
  
 when building pynini
  report error 
  
  
    /opt/homebrew/opt/openfst/include/fst/lock.h:50:8: error: 'shared_mutex' is unavailable: introduced in macOS 10.12

**Comment by pengzhendong** [comment]
Install pynini with conda:

``` bash
$ conda install -c conda-forge pynini
```

**Comment by fastfading** [comment]
there is no issue with pynini 2.1.6  

but this lib depend on   pynini 2.1.5  , which could not be supported by m1 mac .    
could you consider to upgrade the pynini dependency .
