### ISSUE TITLE
【itn】满足七乘二十四个小时

### ISSUE THREAD

**Issue by lucky-dreamer-nn** [wenet-e2e/WeTextProcessing#264]
输入文本：满足七乘二十四个小时
输出：
char { value: "满" } char { value: "足" } math { value: "7×2" } measure { value: "14个" } char { value: "小" } char { value: "时" }
满足7×214个小时

希望输出：满足7×24个小时

请问math和measure有重叠或者有冲突的时候，可以怎么解决如上问题呢？

**Comment by xingchensong** [comment]
加白名单，可以提个pr
