### ISSUE TITLE
数字TN问题

### ISSUE THREAD

**Issue by ruby11dog** [wenet-e2e/WeTextProcessing#268]
想去医院检查,我立刻表示关心,说500也行啊-》['想', '去', '医', '院', '检', '查', ',', '我', '立', '刻', '表', '示', '关', '心', ',', '说', '五', '零', '零', '也', '行', '阿', '.']
500希望是”五百“而不是“五零零”

**Comment by xingchensong** [comment]
需要自己改一下规则
