### ISSUE TITLE
电话TN不准确

### ISSUE THREAD

**Issue by dawenxi-only** [wenet-e2e/WeTextProcessing#272]
当输入为：“请问你的电话号码是13882366638对吗”
tn.normalize结果为“请问你的电话号码是幺三八八百二十三万六千六百三十八对吗”

当输入为：“请问你的电话号码是13882366638，对吗”
tn.normalize结果为“请问你的电话号码是幺三八八二三六六六三八对吗”

发现电话号码后面有标点符号时，可以正确识别，无标点符号时，不能正确识别

**Comment by pengzhendong** [comment]
我猜因为“对”字是单位

**Comment by dawenxi-only** [comment]
是的，请问这个怎么解决呢

**Comment by pengzhendong** [comment]
最简单的是删掉这一行：https://github.com/wenet-e2e/WeTextProcessing/blob/a8efdf731b0153edb97e2a1a73268f3b2d38e901/tn/chinese/data/measure/units_zh.tsv#L75
然后重新构图，或者我们看看如何改一下权重。

**Comment by dawenxi-only** [comment]
删除units_zh中的对解决了我的问题，非常感谢。
