### ISSUE TITLE
你好啊   -> 你好

### ISSUE THREAD

**Issue by xiaoqiang-ok** [wenet-e2e/WeTextProcessing#274]
语气词被略掉了怎么办如

**Comment by xiaoqiang-ok** [comment]
语气词被过滤掉了（如： 你好啊  -----tn----》你好），不想被过滤怎么办？
from tn.chinese.normalizer import Normalizer as ZhNormalizer
_wetts_zh_tn_model = ZhNormalizer(remove_erhua=True, overwrite_cache=False)
text = "你好啊"
text2 = _wetts_zh_tn_model.normalize(text)
print(text2)#"你好"

**Comment by pengzhendong** [comment]
`remove_interjections=False`

**Comment by xiaoqiang-ok** [comment]
我是安装WeTextProcessing  python包（pip install WeTextProcessing），然后调用的，增加这个remove_interjections=False,似乎不起作用


from tn.chinese.normalizer import Normalizer as ZhNormalizer
_wetts_zh_tn_model = ZhNormalizer(remove_erhua=False, **remove_interjections=False,** overwrite_cache=False)
text = "你好啊"
text2 = _wetts_zh_tn_model.normalize(text)
print(text2)#"你好"
![badcase_20240829123844](https://github.com/user-attachments/assets/ca2b8980-e72c-4ed2-aef5-3da23082c357)
