### ISSUE TITLE
适配arm机器安装python包失败

### ISSUE THREAD

**Issue by xiaoqiang-ok** [wenet-e2e/WeTextProcessing#276]
机器cpu：
![image](https://github.com/user-attachments/assets/e2cc04ed-b3c9-4643-a533-7eb48d1acc6e)
系统：
cat /proc/version
Linux version 4.19.90-vhulk2211.3.0.h1804.eulerosv2r10.aarch64 (abuild@szxrtosci10000) (gcc version 7.3.0 (GCC)) #1 SMP Mon Jun 3 18:15:36 UTC 2024
安装适配arm机器安装失败
![arm64架构环境适配问题](https://github.com/user-attachments/assets/0bf68da5-2986-4fc7-8bad-1e74b9cdbfae)

**Comment by xiaoqiang-ok** [comment]
error seems to come from openfst，

**Comment by LiuShixing** [comment]
同样的问题，请问你解决了吗？

**Comment by FredWe** [comment]
My commands can handle pynini installation related issues:

1. use a conda environment
2. `conda install pynini -c conda-forge` to use a pynini conda package instead of compiling yourself
3. `sed -i '' 's/pynini==[0-9\.]*/pynini/' requirements.txt` to remove pynini pip version limit so you can pip install smoothly

Enjoy it.

**Comment by Direct-A** [comment]
I used macos, and I met the same problem.
I've solved this problem now.

1. `conda install openfst`
2. Find directory `fst` path, for me is `/opt/homebrew/Caskroom/miniforge/base/envs/tts/include/fst`
3. Use `env CXXFLAGS="-I/opt/homebrew/Caskroom/miniforge/base/envs/tts/include" LDFLAGS="-L/opt/homebrew/Caskroom/miniforge/base/envs/tts/lib" pip install WeTextProcessing` to install.
4. Waiting for install successful. Good luck for you.

**Comment by chenmj201601** [comment]
> My commands can handle pynini installation related issues:
> 
> 1. use a conda environment
> 2. `conda install pynini -c conda-forge` to use a pynini conda package instead of compiling yourself
> 3. `sed -i '' 's/pynini==[0-9\.]*/pynini/' requirements.txt` to remove pynini pip version limit so you can pip install smoothly
> 
> Enjoy it.

 `conda install pynini -c conda-forge` ，The following packages are not available from current channels.

**Comment by chenmj201601** [comment]
> I used macos, and I met the same problem. I've solved this problem now.
> 
> 1. `conda install openfst`
> 2. Find directory `fst` path, for me is `/opt/homebrew/Caskroom/miniforge/base/envs/tts/include/fst`
> 3. Use `env CXXFLAGS="-I/opt/homebrew/Caskroom/miniforge/base/envs/tts/include" LDFLAGS="-L/opt/homebrew/Caskroom/miniforge/base/envs/tts/lib" pip install WeTextProcessing` to install.
> 4. Waiting for install successful. Good luck to you.

this way, when `Building wheel for pynini (pyproject.toml) ...`, it will cost long time and can not complete!

![image](https://github.com/user-attachments/assets/331faa84-d9fd-47ed-9bad-d8300530bd09)

**Comment by pengzhendong** [comment]
如果你只是想做推理，可以在别的平台构图，我建议你先用这个：https://github.com/pengzhendong/wetext

**Comment by chenmj201601** [comment]
> 如果你只是想做推理，可以在别的平台构图，我建议你先用这个（不依赖 pynini，依赖的 kaldifst 有提供 arm 适配）：https://github.com/pengzhendong/wetext

谢谢

**Comment by xiaoqiang-ok** [comment]
> My commands can handle pynini installation related issues:
> 
> 1. use a conda environment
> 2. `conda install pynini -c conda-forge` to use a pynini conda package instead of compiling yourself
> 3. `sed -i '' 's/pynini==[0-9\.]*/pynini/' requirements.txt` to remove pynini pip version limit so you can pip install smoothly
> 
> Enjoy it.
我这里报错：
![Image](https://github.com/user-attachments/assets/0fc850df-a8f5-4555-93e3-d94eba1475b3)
