### ISSUE TITLE
调转原有文本顺序的规则（10公里/小时--》每小时十公里）怎么移除？

### ISSUE THREAD

**Issue by xiaoqiang-ok** [wenet-e2e/WeTextProcessing#279]
有些规则会调转原有文本的顺序，这会影响我后续的一些文本对齐，这种规则怎么拿掉比较好？
eg：
10**公里**/**小时**  TN转成   每**小时**十**公里**

**Comment by pengzhendong** [comment]
参考这里：https://github.com/wenet-e2e/WeTextProcessing/blob/d1e20901a601618fe311b57efd0c26c54f6b3125/tn/chinese/rules/measure.py#L61-L64
