### ISSUE TITLE
为何itn之后的字符不是连续的，而是一行一行的

### ISSUE THREAD

**Issue by yjinhui** [wenet-e2e/WeTextProcessing#280]
eg：
共4
6
5
篇约3
1
5
万字

**Comment by yjinhui** [comment]
![企业微信截图_17288900574891](https://github.com/user-attachments/assets/05c7a834-c6a5-45a3-ba46-9f543ea54399)
这样za在py脚本里调用是有问题的吗

**Comment by yjinhui** [comment]
![image](https://github.com/user-attachments/assets/5e7a6490-f302-4002-aa3f-cc65abf0c2cb)

**Comment by xingchensong** [comment]
用shell，不要用vscode的终端

**Comment by yjinhui** [comment]
谢谢，换了shell可以了，ubuntu下vscode的终端也可以了
