### ISSUE TITLE
数值断句引起的歧义。比分是十一比七十一比六

### ISSUE THREAD

**Issue by EAGLE50** [wenet-e2e/WeTextProcessing#282]
在ASR模型中使用了ITN，在乒乓球比赛中，主持人讲“前两场的比分是11：7，11：6”想表达的是这个意思。但ASR转出来的文本是“前两场的比分是十一比七十一比六”，经过ITN处理后，变成“前两场的比分是11：71：6”。
尝试过的方案：
1.修改math的规则，去掉“比”。结果是“前两场的比分是11比71比六”。
发现根本原因是Cardinal的规则导致的。想使用白名单
2.使用白名单，构建了这样数据对：十一比七   十一比七  ，并调整了权重，但无效。

请问这种情况有解决方案吗？

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/WeTextProcessing/issues/177
