### ISSUE TITLE
another badcase

### ISSUE THREAD

**Issue by ranchlai** [wenet-e2e/WeTextProcessing#31]
In [14]: >>> from tn.chinese.normalizer import Normalizer
    ...: >>> normalizer = Normalizer()
    ...: >>> normalizer.normalize("12.5平方电线")
Out[14]: '十二月五日平方电线'

**Comment by xingchensong** [comment]
just add "平方" to `tn/chinese/data/measure/units_zh.tsv`, feel free to make a PR, : )

**Comment by xingchensong** [comment]
fixed, https://github.com/wenet-e2e/WeTextProcessing/pull/33
