### ISSUE TITLE
TN运行速度很慢

### ISSUE THREAD

**Issue by lesswrongzh** [wenet-e2e/WeTextProcessing#44]
我在本地跑python解析一句话需要200ms左右，用C++ runtime速度也很慢

**Comment by pengzhendong** [comment]
<img width="697" alt="b5a12845e9c43b408e0edbe42568a97" src="https://user-images.githubusercontent.com/10704539/199219284-ea28fc2c-659f-4948-8602-1ee1f388970a.png">

得看一句话有多长，我这里 27 句话 180ms，平均一句话 7ms。

**Comment by pengzhendong** [comment]
猜测你实例化 normalizer 的代码放到循环里面了，下面这行代码执行一次即可。

``` python
normalizer = Normalizer()
```
