### ISSUE TITLE
units_zh.tsv 真的一点都没有参考 PaddleSpeech TN 么？

### ISSUE THREAD

**Issue by yt605155624** [wenet-e2e/WeTextProcessing#47]
- https://github.com/wenet-e2e/WeTextProcessing/blob/master/tn/chinese/data/measure/units_zh.tsv 
- https://github.com/PaddlePaddle/PaddleSpeech/blob/9aab706cba2f2a3ec4d326bc91b9a9423e503a95/paddlespeech/t2s/frontend/zh_normalization/num.py#L31

**Comment by pengzhendong** [comment]
从这抄的：https://github.com/NVIDIA/NeMo/blob/main/nemo_text_processing/text_normalization/zh/data/measure/units_zh.tsv

**Comment by yt605155624** [comment]
本想问问他们是不是参考我们的，但是难为外国 repo 没啥意思 = =

**Comment by pengzhendong** [comment]
国产不更应该团结吗？🥺

**Comment by yt605155624** [comment]
🤝
