### ISSUE TITLE
连续进行ITN时，tokens缓存没有清空

### ISSUE THREAD

**Issue by y00281951** [wenet-e2e/WeTextProcessing#51]
不知道是不是我调的有问题，在对partial_result连续做ITN，以及final_result做ITN时，结果会不断累集。
比如：今天天气怎么样->今天今天天气今天天气怎么样
是否需要在reorder之后清空tokens
std::string TokenParser::reorder(const std::string& input) 
153行后，tokens.clear()

**Comment by xingchensong** [comment]
你怎么调用的，c++接口输出只和输入有关系，出现这个结果可能大概率中间结果送进去的时候就是这样累积的了

**Comment by y00281951** [comment]
基于用户体验考虑，中间结果也会调用。但是这个tokens是全局变量，是否应该每次调用都清空合理？

**Comment by xingchensong** [comment]
又看了一下，您说的是对的，可以提个pr~

**Comment by xingchensong** [comment]
fixed https://github.com/wenet-e2e/WeTextProcessing/pull/56
