### ISSUE TITLE
中英混合时，badcase

### ISSUE THREAD

**Issue by y00281951** [wenet-e2e/WeTextProcessing#54]
[StringFstToOutputLabels: Invalid start state](string.h:123] StringFstToOutputLabels: Invalid start state)

**Comment by xingchensong** [comment]
检查是否有非法输入，比如颜文字啥的

**Comment by y00281951** [comment]
我试了下python没问题，应该是我punc引入的非utf8字符，我再确认一下

**Comment by y00281951** [comment]
utf8拆字符串时出的错，需要把尾部三个字节去掉再做utf8的操作，不然有非法字符
