### ISSUE TITLE
add new language

### ISSUE THREAD

**Issue by cnlinxi** [wenet-e2e/WeTextProcessing#60]
I hope to use NeMo resource to add new languages in this project. Can you give me some guidelines?

Thanks a lot :)

**Comment by xingchensong** [comment]
THX! Simply follow the directory structure (example: https://github.com/wenet-e2e/WeTextProcessing/pull/8), there has no extra requirement.

![image](https://user-images.githubusercontent.com/13466943/204233067-a4b60bc0-db19-433b-bd29-475971af412e.png)

**Comment by cnlinxi** [comment]
Thank you very much. I will study it carefully :)
