### ISSUE TITLE
FST里的id对应关系

### ISSUE THREAD

**Issue by 1215thebqtic** [wenet-e2e/WeTextProcessing#67]
正在学习怎么写规则，有两个问题想要请教一下，谢谢

1. 我把中间结果进行了打印，但不是很清楚input/output label的对应关系是什么，猜测48对应的可能是“零”，请问如何知道字符和id号之间的对应关系呢？
>>> from pynini import string_file
>>> zero = string_file('tn/chinese/data/number/zero.tsv')
>>> print(zero)
0       1       48      0
1       2       0       0
2       3       0       233
3       4       0       155
4       5       0       182
5

2.  我只想把手机电话号码中的“一”改成“幺”，也就是说如果一个数是11位的话，就把“一”改成“幺”，其他情况不变，请问这个有没有什么好的实现方法呢？我看之前有一版是有“幺”的存在的，但好像是针对所有一和幺的：https://github.com/wenet-e2e/WeTextProcessing/commit/5462c72c075bdb69cedad8c8f98c783f325b3ba1

 谢谢

**Comment by pengzhendong** [comment]
汉字在 UTF8 中对应三个字节，每条弧上记录一个字节。
![image](https://user-images.githubusercontent.com/10704539/205890216-9a8d0691-202e-44b8-9d18-46919aacd753.png)

**Comment by pengzhendong** [comment]
你可以定义一个规则，长度是十一位数，然后 cost 比 cardinal 低。（你不处理类似 12306 这种？）

**Comment by 1215thebqtic** [comment]
> 汉字在 UTF8 中对应三个字节，每条弧上记录一个字节。 ![image](https://user-images.githubusercontent.com/10704539/205890216-9a8d0691-202e-44b8-9d18-46919aacd753.png)

原来如此谢谢！可以问下这个图你是用什么工具画出来的吗？fstdraw吗？


> 你可以定义一个规则，长度是十一位数，然后 cost 比 cardinal 低。（你不处理类似 12306 这种？）

好的感谢我去试试，现在文本里没12306，都是手机号，所以先处理手机号。虽然还没太看懂...12306这种常用的是不是需要放白名单就好

**Comment by pengzhendong** [comment]
我是在 colab 里跑的，会自动画图，用 jupyter 也可以。

**Comment by 1215thebqtic** [comment]
好的谢谢！！其他规则我暂时还没看到，等看到后我可以再提issue
有个badcase还麻烦你帮忙看一下，我把手机号按照你说的加了个简单的规则tn/chinese/rules/mobilephonenum.py
```
class MobilePhoneNum(Processor):

    def __init__(self):
        super().__init__(name='mobilephonenum')
        self.build_tagger()
        self.build_verbalizer()

    def build_tagger(self):
        digit = string_file('tn/chinese/data/number/digityao.tsv')
        zero = string_file('tn/chinese/data/number/zero.tsv')

        mobilephonenum = digit + (digit | zero)**10
        tagger = insert('value: "') + mobilephonenum + insert('"')
        self.tagger = self.add_tokens(tagger)
```
又把电话号码放到了前面
```
        tagger = (add_weight(date, 1.02)
                  | add_weight(whitelist, 1.03)
                  | add_weight(sport, 1.04)
                  | add_weight(mobilephonenum, 1.04)
                  | add_weight(fraction, 1.05)
                  | add_weight(measure, 1.05)
                  | add_weight(money, 1.05)
                  | add_weight(time, 1.05)
                  | add_weight(cardinal, 1.06)
                  | add_weight(math, 1.08)
                  | add_weight(char, 100)).optimize().star

```
有句话是这样的：“18833332111更换”
输出：
cardinal { value: "一八八" } measure { value: "三千三百三十三万两千一百一十一更" } char { value: "换" }
一八八三千三百三十三万两千一百一十一更换
看了下“更”是一个单位，但是我把电话号码也放到了单位的前面，为什么会出现这种情况呢？是我哪里写错了吗？谢谢~

**Comment by pengzhendong** [comment]
你可以把单位中的更删掉
