### ISSUE TITLE
[Known Issue] The "delete" function in Verblizer introduces additional null ('\0') characters. 

### ISSUE THREAD

**Issue by xingchensong** [wenet-e2e/WeTextProcessing#84]
When using the UTF-8 "string2char" function [link](https://github.com/wenet-e2e/WeTextProcessing/blob/master/runtime/utils/utf8_string.cc#L56-L63), these null ('\0') characters are explicitly separated. However, when using standard "std::out", these null characters are automatically filtered out. 

If you do want use "string2char", a simple solution is to remove the null characters through post-processing:

```cpp
// TODO(zhendong.peng): Figured out this!
std::string output = Verbalize(input);
output.erase(std::remove(output.begin(), output.end(), '\0'), output.end());
std::vector<std::string> chars;
string2chars(output, &chars);
```

**Comment by pengzhendong** [comment]
The printer (openfst < 1.7.2) may produce '\0' in the output.
