### ISSUE TITLE
日期有一些问题

### ISSUE THREAD

**Issue by locasxe** [wenet-e2e/WeTextProcessing#90]
例如，两千一零年会逆正则成21000年，这种问题该怎么解决呢

**Comment by locasxe** [comment]
> 这个不是一个特别标准的读法，只能case-by-case地修改，修改方法可以阅读下文章第四节 https://mp.weixin.qq.com/s/q_11lck78qcjylHCi6wVsQ

但是，像两千零十这种数字类型的转换成2000010，感觉不是很对劲？

**Comment by xingchensong** [comment]
谢谢指正！这是个bug，已经修复，参见 https://github.com/wenet-e2e/WeTextProcessing/pull/91
