### ISSUE TITLE
如何更改时间的位置？

### ISSUE THREAD

**Issue by standyyyy** [wenet-e2e/WeTextProcessing#92]
大佬好呀 ，我想咨询一下如何修改时间上的位置？
比如：早上七点二十五叫我
INT之后是：7:25 a.m 叫我
我将data里面的time中文件中的英文都改成中文了。
效果就变成了：7:25早上叫我
然后我想更改一下位置 ，改成：早上7:25叫我

跟着代码去了time.py之后，把
`verbalizer = (hour + addcolon + minute +
                      (addcolon + second).ques + noon.ques)`
改成了
`verbalizer = (noon.ques+hour + addcolon + minute +
                      (addcolon + second).ques )`
结果发现会报错 ，是不是因为tagger没有一起修改？
如果想改要改一下这个顺序，该如何做，大佬指点一下

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/WeTextProcessing/blob/master/tn/token_parser.py#L29

这里把noon放前面，其他的别动应该就行了

**Comment by standyyyy** [comment]
不行 ，会报错，在分词的时候是在前面。
![image](https://github.com/wenet-e2e/WeTextProcessing/assets/39285732/9bee95fe-c573-471a-89ee-83d2b2180b99)
`Traceback (most recent call last):
  File "D:\PyCharm 2022.1.4\plugins\python\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm 2022.1.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/whisper_Project/test_punc.py", line 13, in <module>
    print(invnormalizer.normalize("早上七点二十五叫我,长远一点，一路往下跌，现在是一点三十分，没有没有到万亿啊，没到万亿八千五百九十一，八千五百九十一啊，跟昨天好像还说了一点点啊。"))
  File "E:\whisper_Project\TextProcessing\tn\processor.py", line 106, in normalize
    return self.verbalize(self.tag(input))
  File "E:\whisper_Project\TextProcessing\tn\processor.py", line 103, in verbalize
    return shortestpath(lattice, nshortest=1, unique=True).string()
  File "extensions\_pynini.pyx", line 462, in _pynini.Fst.string
  File "extensions\_pynini.pyx", line 507, in _pynini.Fst.string
_pywrapfst.FstOpError: Operation failed
`
在lattice = escape(output) @ self.verbalizer出来是空的。

**Comment by xingchensong** [comment]
不好意思，昨天miss掉了，rules/time.py 也要改一下

![image](https://github.com/wenet-e2e/WeTextProcessing/assets/13466943/07d4705f-1766-4126-b56f-c87149bc13f6)

```sh
diff --git a/itn/chinese/rules/time.py b/itn/chinese/rules/time.py                                                                                                                                                   index 27d6901..855726b 100644
--- a/itn/chinese/rules/time.py
+++ b/itn/chinese/rules/time.py
@@ -40,10 +40,10 @@ class Time(Processor):

     def build_verbalizer(self):
         addcolon = insert(':')
-        hour = delete('hour: "') + self.SIGMA + delete('"')
+        noon = delete('noon: "') + self.SIGMA + delete('"')
+        hour = delete(' hour: "') + self.SIGMA + delete('"')
         minute = delete(' minute: "') + self.SIGMA + delete('"')
         second = delete(' second: "') + self.SIGMA + delete('"')
-        noon = delete(' noon: "') + self.SIGMA + delete('"')
-        verbalizer = (hour + addcolon + minute +
-                      (addcolon + second).ques + noon.ques)
+        verbalizer = (noon.ques + hour + addcolon + minute +
+                      (addcolon + second).ques)
         self.verbalizer = self.delete_tokens(verbalizer)
diff --git a/tn/token_parser.py b/tn/token_parser.py
index ef32222..f42e26a 100644
--- a/tn/token_parser.py
+++ b/tn/token_parser.py
@@ -26,7 +26,7 @@ ITN_ORDERS = {
     'fraction': ['sign', 'numerator', 'denominator'],
     'measure': ['numerator', 'denominator', 'value'],
     'money': ['currency', 'value'],
-    'time': ['hour', 'minute', 'second', 'noon']}
+    'time': ['noon', 'hour', 'minute', 'second']}
```

测试结果：
![image](https://github.com/wenet-e2e/WeTextProcessing/assets/13466943/7585bd06-c76e-40d6-a06a-fb87e883a0d3)

**Comment by standyyyy** [comment]
![image](https://github.com/wenet-e2e/WeTextProcessing/assets/39285732/51fa13be-6940-4d8b-aae1-2788bd8cd6d8)
奇怪 ，我改这两个怎么跑会报错，我还特地重新拉了下最新的代码。

**Comment by xingchensong** [comment]
44行，是 `delete(' hour: "')` 不是 `delete('hour: "')`, 注意有个空格

**Comment by standyyyy** [comment]
![image](https://github.com/wenet-e2e/WeTextProcessing/assets/39285732/fd45fbc1-24ff-45fe-8fa6-090e64005ec9)
奇怪，已经加上了，还是会报错，大佬能不能上传个分支我拉一下试试看？

**Comment by xingchensong** [comment]
你在36行的那个改动需要去掉

**Comment by standyyyy** [comment]
抱歉，有点粗心，这个是因为改错了，所以以为是上面没改，所以尝试了下 。
现在改回去了 。
![image](https://github.com/wenet-e2e/WeTextProcessing/assets/39285732/0786fd19-3090-42e3-81fb-a645c480b93d)

**Comment by standyyyy** [comment]
成功啦，谢谢大佬哈，抱歉，之前估计是不知道哪里改动了没改回来导致的问题 ，重新拉了个新的在尝试就好了。
![image](https://github.com/wenet-e2e/WeTextProcessing/assets/39285732/f35c6ba0-5b7a-452e-9269-7f41481c8e13)

**Comment by standyyyy** [comment]
我知道为什么报错了，是因为字数太长了报错 。我减少一点字就不会报错了。
我用的是下面这段文字
`text = 早上七点二十五叫我,长远一点，一路往下跌，我有一种草，我有一点点，现在是一点三十分，没有没有到万亿啊，没到万亿八千五百九十一，八千五百九十一啊，跟昨天好像还说了一点点啊，然后你用金发绿，另外一个捕捞季节给了一个金叉啊，给了一个金叉啊，这个金叉能走几天，我也不知道啊，这真不知道。`

**Comment by fxyouruo** [comment]
> 我知道为什么报错了，是因为字数太长了报错 。我减少一点字就不会报错了。 我用的是下面这段文字 `text = 早上七点二十五叫我,长远一点，一路往下跌，我有一种草，我有一点点，现在是一点三十分，没有没有到万亿啊，没到万亿八千五百九十一，八千五百九十一啊，跟昨天好像还说了一点点啊，然后你用金发绿，另外一个捕捞季节给了一个金叉啊，给了一个金叉啊，这个金叉能走几天，我也不知道啊，这真不知道。`

您好！按照这样修改，比如遇到“七点二十五分”，没有“早上”，会不会报错呢？我直接这样修改，遇到了ERROR: StringFstToOutputLabels: Invalid start state的错误。
