### ISSUE TITLE
[TN/number] number规则基于半角数字，如果输入是全角数字，不会被转换 

### ISSUE THREAD

**Issue by xingchensong** [wenet-e2e/WeTextProcessing#94]
![80802bffe7eb2a747c2493a5c1ecabd](https://github.com/wenet-e2e/WeTextProcessing/assets/13466943/5172c5db-619e-4706-9e16-5cfd4804d1d4)

全角数字没有被number.fst转换，最后被postprocess.fst转了半角

**Comment by pengzhendong** [comment]
之前全角转半角是在 preprocesser 中完成，但是`。`有可能被转成`.`，进而导致`1。2`被转成`一点二`。

**Comment by xingchensong** [comment]
尝试在preprocesore中加入fuu2half后，编译阶段会爆内存（PS：在23G内存的机器上也试过，同样会爆）

![image](https://github.com/wenet-e2e/WeTextProcessing/assets/13466943/5e9e2071-4d13-427e-85ce-8c3ff2a1d9a8)
